#!/usr/bin/env python3

from json import load
from sys import argv

def loc(nb):
    with open(nb, 'r') as f:
        cells = load(f)['cells']
    return sum(len(c['source']) for c in cells if c['cell_type'] == 'code')

def run(ipynb_files):
    return sum(loc(nb) for nb in ipynb_files)

if __name__ == '__main__':
    print(run(argv[1:]))
