#!/usr/bin/osascript
on run argv
  tell application "Messages"
    set messages to (items 4 thru -1 of argv)
    repeat (item 2 of argv) times 
      set msg to some item of messages
      send msg to participant (item 1 of argv)
      delay (item 3 of argv)
    end repeat
  end tell
end run
